"""Offline group-theoretic catalogue construction for H0-D."""

from .affine_quotient import (
    AffineQuotient,
    CompactDisplacementAction,
    PrimitiveSpaceGroup,
    TranslationQuotient,
    build_compact_displacement_action,
    canonical_supercell_orbits,
    enumerate_upper_hnfs,
    primitive_space_group_from_hall,
    real_irrep_multiplicity,
    standard_hall_numbers,
)
from .finite_group import (
    FiniteGroup,
    OPDClass,
    RealIrrep,
    canonical_stabilizer_key,
    enumerate_fixed_space_projectors,
    enumerate_opd_classes,
    enumerate_real_irreps,
    intersect_stabilizer_bitsets,
    stabilizer_bitset,
)
from .parent_decomposition import (
    DecompositionResult,
    ParentCandidate,
    StandardCrystal,
    balanced_selection,
    decompose_parent_candidate,
    find_parent_candidates,
    standardize_crystal,
    translation_quotient_displacement,
)
from .parent_projection import (
    ParentProjection,
    conjugate_embedding_to_primitive,
    project_lattice_metric,
    project_translationengleiche_parent,
)
from .path_measure import RealizedPathClass, allocate_reference_measure
from .subgroup_embeddings import (
    AffineInclusionCertificate,
    RationalAffineTransform,
    certify_affine_subgroup_inclusion,
    normalized_relation_variant,
    species_wyckoff_exact_cover,
    wyckoff_multiset_has_exact_cover,
)

__all__ = [
    "AffineQuotient",
    "AffineInclusionCertificate",
    "CompactDisplacementAction",
    "FiniteGroup",
    "OPDClass",
    "PrimitiveSpaceGroup",
    "RealIrrep",
    "RealizedPathClass",
    "RationalAffineTransform",
    "DecompositionResult",
    "ParentCandidate",
    "ParentProjection",
    "StandardCrystal",
    "TranslationQuotient",
    "build_compact_displacement_action",
    "allocate_reference_measure",
    "balanced_selection",
    "canonical_stabilizer_key",
    "certify_affine_subgroup_inclusion",
    "conjugate_embedding_to_primitive",
    "canonical_supercell_orbits",
    "enumerate_fixed_space_projectors",
    "enumerate_opd_classes",
    "enumerate_real_irreps",
    "enumerate_upper_hnfs",
    "decompose_parent_candidate",
    "find_parent_candidates",
    "intersect_stabilizer_bitsets",
    "normalized_relation_variant",
    "real_irrep_multiplicity",
    "primitive_space_group_from_hall",
    "project_lattice_metric",
    "project_translationengleiche_parent",
    "standard_hall_numbers",
    "stabilizer_bitset",
    "species_wyckoff_exact_cover",
    "standardize_crystal",
    "translation_quotient_displacement",
    "wyckoff_multiset_has_exact_cover",
]
