"""Exact finite-group and OPD-isotropy algorithms used by H0-D.

The runtime generator does not depend on this module.  H0-D uses it offline to
construct a versioned physical path catalogue from a finite affine quotient.
The group elements must already be in canonical key order; this makes the
result independent of source enumeration order.
"""

from __future__ import annotations

from collections import deque
from dataclasses import dataclass
from typing import Iterable

import numpy as np
from numpy.typing import NDArray

IntArray = NDArray[np.int64]
FloatArray = NDArray[np.float64]


@dataclass(frozen=True)
class FiniteGroup:
    """A finite group represented by a Cayley table and stable element keys."""

    table: IntArray
    element_keys: tuple[str, ...]
    identity: int
    inverses: IntArray

    @classmethod
    def from_cayley_table(
        cls,
        table: NDArray[np.integer],
        element_keys: Iterable[str],
        *,
        check_associativity: bool = True,
    ) -> "FiniteGroup":
        values = np.asarray(table, dtype=np.int64)
        keys = tuple(element_keys)
        if values.ndim != 2 or values.shape[0] != values.shape[1] or values.shape[0] < 1:
            raise ValueError("Cayley table must be a nonempty square integer matrix")
        order = values.shape[0]
        if len(keys) != order or len(set(keys)) != order:
            raise ValueError("finite-group element keys must be unique and table-aligned")
        if np.any(values < 0) or np.any(values >= order):
            raise ValueError("Cayley table contains an out-of-range element index")
        expected = np.arange(order, dtype=np.int64)
        if any(not np.array_equal(np.sort(row), expected) for row in values):
            raise ValueError("every Cayley-table row must be a permutation")
        if any(not np.array_equal(np.sort(column), expected) for column in values.T):
            raise ValueError("every Cayley-table column must be a permutation")
        identities = [
            index
            for index in range(order)
            if np.array_equal(values[index], expected) and np.array_equal(values[:, index], expected)
        ]
        if len(identities) != 1:
            raise ValueError("Cayley table must contain exactly one two-sided identity")
        identity = identities[0]
        inverses = np.empty(order, dtype=np.int64)
        for left in range(order):
            candidates = np.flatnonzero(
                (values[left] == identity) & (values[:, left] == identity)
            )
            if candidates.size != 1:
                raise ValueError("every group element must have one two-sided inverse")
            inverses[left] = int(candidates[0])
        if check_associativity:
            for left in range(order):
                lhs = values[values[left, :, None], expected[None, :]]
                rhs = values[left, values]
                if not np.array_equal(lhs, rhs):
                    raise ValueError("Cayley table is not associative")
        return cls(values, keys, identity, inverses)

    @property
    def order(self) -> int:
        return self.table.shape[0]

    def conjugate(self, element: int, by: int) -> int:
        """Return ``by * element * by^-1``."""
        return int(self.table[self.table[by, element], self.inverses[by]])

    def subgroup_closure(self, generators: Iterable[int]) -> tuple[int, ...]:
        """Return the subgroup generated by ``generators`` in sorted index order."""
        selected = {self.identity}
        frontier = deque(int(value) for value in generators)
        while frontier:
            value = frontier.popleft()
            if not 0 <= value < self.order:
                raise ValueError("subgroup generator lies outside the finite group")
            if value not in selected:
                selected.add(value)
            current = tuple(selected)
            for left in current:
                for product in (self.table[left, value], self.table[value, left]):
                    product_int = int(product)
                    if product_int not in selected:
                        selected.add(product_int)
                        frontier.append(product_int)
            inverse = int(self.inverses[value])
            if inverse not in selected:
                selected.add(inverse)
                frontier.append(inverse)
        changed = True
        while changed:
            changed = False
            current = tuple(selected)
            for left in current:
                for right in current:
                    product = int(self.table[left, right])
                    if product not in selected:
                        selected.add(product)
                        changed = True
        return tuple(sorted(selected))

    def enumerate_subgroups(self) -> tuple[tuple[int, ...], ...]:
        """Enumerate every subgroup without relying on generator order."""
        trivial = (self.identity,)
        known = {trivial}
        queue = deque([trivial])
        while queue:
            subgroup = queue.popleft()
            present = set(subgroup)
            for element in range(self.order):
                if element in present:
                    continue
                generated = self.subgroup_closure((*subgroup, element))
                if generated not in known:
                    known.add(generated)
                    queue.append(generated)
        return tuple(sorted(known, key=lambda values: (len(values), values)))

    def generators(self) -> tuple[int, ...]:
        """Return a deterministic small generating set.

        A homomorphism only needs to be checked for left multiplication by a
        generating set and every group element.  This is exactly equivalent
        to the quadratic all-pairs check, while avoiding a large temporary
        ``[|G|, |G|, d, d]`` tensor.
        """
        generators: list[int] = []
        generated = (self.identity,)
        for element in range(self.order):
            if element in generated:
                continue
            generators.append(element)
            generated = self.subgroup_closure(generators)
            if len(generated) == self.order:
                break
        if len(generated) != self.order:
            raise RuntimeError("failed to construct a generating set")
        return tuple(generators)


@dataclass(frozen=True)
class RealIrrep:
    """One physically irreducible real representation."""

    matrices: FloatArray
    frobenius_schur_indicator: int
    character_key: tuple[float, ...]

    @property
    def dimension(self) -> int:
        return self.matrices.shape[1]

    @property
    def complex_regular_contribution(self) -> int:
        """Contribution of this physical real irrep to complex regular completeness."""
        divisors = {1: 1, 0: 2, -1: 4}
        divisor = divisors.get(self.frobenius_schur_indicator)
        if divisor is None or self.dimension**2 % divisor:
            raise RuntimeError("invalid physical-real irrep dimension/indicator pair")
        return self.dimension**2 // divisor


def _left_regular_representation(group: FiniteGroup) -> NDArray[np.complex128]:
    regular = np.zeros((group.order, group.order, group.order), dtype=np.complex128)
    columns = np.arange(group.order)
    for element in range(group.order):
        regular[element, group.table[element, columns], columns] = 1.0
    return regular


def _rounded_tuple(values: NDArray[np.floating], *, decimals: int = 10) -> tuple[float, ...]:
    rounded = np.round(np.asarray(values, dtype=np.float64), decimals=decimals)
    rounded[np.abs(rounded) < 10.0 ** (-decimals)] = 0.0
    return tuple(float(value) for value in rounded.ravel())


def enumerate_real_irreps(group: FiniteGroup) -> tuple[RealIrrep, ...]:
    """Enumerate the complete physically irreducible real representations.

    ``spgrep`` is pinned by the H0-D protocol.  We use its regular-
    representation decomposition rather than its crystallographic little-group
    API, because the input here is the complete finite affine quotient.
    """
    from spgrep.rep.enumerate import enumerate_unitary_irreps_from_regular_representation
    from spgrep.symmetry.pir import _make_physically_irreps_from_complex

    complex_irreps = enumerate_unitary_irreps_from_regular_representation(
        _left_regular_representation(group), rtol=1e-10, max_num_random_generations=16
    )
    if sum(irrep.shape[1] ** 2 for irrep in complex_irreps) != group.order:
        raise RuntimeError("complex irreducible representations are not complete")
    real_irreps, indicators = _make_physically_irreps_from_complex(
        complex_irreps,
        kpoint=None,
        atol=1e-10,
        max_num_random_generations=16,
    )
    output: list[RealIrrep] = []
    for matrices, indicator in zip(real_irreps, indicators):
        real = np.asarray(matrices, dtype=np.float64)
        identity = np.eye(real.shape[1])
        gram = np.einsum("gji,gjk->gik", real, real, optimize=True)
        if not np.allclose(gram, identity[None, :, :], atol=1e-9, rtol=1e-9):
            raise RuntimeError("spgrep returned a non-orthogonal physical real irrep")
        if not np.allclose(real[group.identity], identity, atol=1e-9, rtol=1e-9):
            raise RuntimeError("physical real irrep does not map the identity to I")
        # Generator-by-group verification is a complete homomorphism proof:
        # induction on generator words covers every left factor in G.  It is
        # substantially smaller than materializing all |G|^2 matrix products.
        generators = np.asarray(group.generators(), dtype=np.int64)
        products = np.einsum(
            "aij,hjk->ahik", real[generators], real, optimize=True
        )
        if not np.allclose(
            products, real[group.table[generators]], atol=1e-9, rtol=1e-9
        ):
            raise RuntimeError("physical real irrep violates the group homomorphism")
        character = np.trace(real, axis1=1, axis2=2)
        output.append(RealIrrep(real, int(indicator), _rounded_tuple(character)))
    if sum(irrep.complex_regular_contribution for irrep in output) != group.order:
        raise RuntimeError("physical real irreps are not complete")
    return tuple(sorted(output, key=lambda irrep: (irrep.dimension, irrep.character_key)))


@dataclass(frozen=True)
class OPDClass:
    """One basis- and domain-quotiented order-parameter fixed-space class."""

    physical_key: str
    fixed_dimension: int
    stabilizer: tuple[int, ...]
    stabilizer_words: tuple[int, ...]
    projector: FloatArray


def stabilizer_bitset(stabilizer: Iterable[int], *, group_order: int) -> tuple[int, ...]:
    """Pack a stabilizer into 64-bit words for constant-cost runtime intersections."""
    if group_order < 1:
        raise ValueError("group order must be positive")
    words = [0] * ((group_order + 63) // 64)
    for element in stabilizer:
        index = int(element)
        if not 0 <= index < group_order:
            raise ValueError("stabilizer element lies outside the finite group")
        words[index // 64] |= 1 << (index % 64)
    return tuple(words)


def intersect_stabilizer_bitsets(*stabilizers: tuple[int, ...]) -> tuple[int, ...]:
    """Intersect equally sized packed stabilizers by exact bitwise AND."""
    if not stabilizers:
        raise ValueError("at least one stabilizer bitset is required")
    width = len(stabilizers[0])
    if width < 1 or any(len(value) != width for value in stabilizers):
        raise ValueError("stabilizer bitsets must have one common positive width")
    output = list(stabilizers[0])
    for value in stabilizers[1:]:
        for word in range(width):
            output[word] &= value[word]
    return tuple(output)


def _pointwise_stabilizer(representation: FloatArray, projector: FloatArray) -> tuple[int, ...]:
    dimension = int(np.rint(np.trace(projector)))
    if dimension == 0:
        return ()
    eigenvalues, eigenvectors = np.linalg.eigh(projector)
    basis = eigenvectors[:, eigenvalues > 0.5]
    transformed = np.einsum("gij,jk->gik", representation, basis, optimize=True)
    error = np.max(np.abs(transformed - basis[None, :, :]), axis=(1, 2))
    return tuple(int(index) for index in np.flatnonzero(error <= 1e-9))


def _projector_key(projector: FloatArray) -> tuple[float, ...]:
    symmetric = 0.5 * (projector + projector.T)
    return _rounded_tuple(symmetric, decimals=8)


def enumerate_fixed_space_projectors(representation: FloatArray) -> tuple[FloatArray, ...]:
    """Enumerate the fixed-space lattice without enumerating group subgroups.

    Every subgroup fixed space is an intersection of element fixed spaces,
    and every such intersection is the fixed space of the subgroup generated
    by those elements.  Closing projectors under

    ``range(P) intersect ker(D(g)-I)``

    therefore produces exactly the same distinct fixed spaces as full
    subgroup enumeration, but quotients out subgroups that act identically in
    this representation before doing expensive OPD work.
    """
    values = np.asarray(representation, dtype=np.float64)
    if values.ndim != 3 or values.shape[1] != values.shape[2]:
        raise ValueError("representation must have shape [group,dimension,dimension]")
    dimension = values.shape[1]
    identity = np.eye(dimension, dtype=np.float64)
    element_constraints = values - identity[None, :, :]
    element_gram = np.einsum(
        "gji,gjk->gik", element_constraints, element_constraints, optimize=True
    )
    projectors: dict[tuple[float, ...], FloatArray] = {
        _projector_key(identity): identity
    }
    queue = deque([identity])
    while queue:
        projector = queue.popleft()
        # Both summands are PSD and their joint kernel is precisely the
        # desired subspace intersection.  Batched eigh evaluates all possible
        # next generators in compiled NumPy rather than a Python loop.
        constraints = (identity - projector)[None, :, :] + element_gram
        eigenvalues, eigenvectors = np.linalg.eigh(constraints)
        retained = eigenvalues <= 1e-8
        candidates = np.einsum(
            "gik,gk,gjk->gij",
            eigenvectors,
            retained.astype(np.float64),
            eigenvectors,
            optimize=True,
        )
        for candidate in candidates:
            candidate = 0.5 * (candidate + candidate.T)
            key = _projector_key(candidate)
            if key in projectors:
                continue
            if not np.allclose(candidate @ candidate, candidate, atol=1e-8, rtol=1e-8):
                raise RuntimeError("fixed-space intersection is not an idempotent projector")
            projectors[key] = candidate
            queue.append(candidate)
    return tuple(
        projectors[key]
        for key in sorted(
            projectors,
            key=lambda value: (int(round(sum(value))), value),
        )
    )


def _domain_key(
    group: FiniteGroup,
    representation: FloatArray,
    projector: FloatArray,
    stabilizer: tuple[int, ...],
) -> str:
    coefficients = np.asarray(
        [np.trace(projector @ matrix) for matrix in representation], dtype=np.float64
    )
    coefficients = np.round(coefficients, decimals=10)
    coefficients[np.abs(coefficients) < 1e-10] = 0.0
    candidates: list[str] = []
    for domain in range(group.order):
        inverse = int(group.inverses[domain])
        permutation = np.asarray(
            [group.table[inverse, group.table[element, domain]] for element in range(group.order)],
            dtype=np.int64,
        )
        conjugated = sorted(group.element_keys[group.conjugate(element, domain)] for element in stabilizer)
        # Pair each coefficient with its stable operation key before sorting;
        # the signature is therefore independent of source enumeration order.
        coefficient_key = ",".join(
            f"{key}:{value:.10g}"
            for key, value in sorted(
                zip(group.element_keys, coefficients[permutation]), key=lambda item: item[0]
            )
        )
        candidates.append("H=" + ";".join(conjugated) + "|C=" + coefficient_key)
    return min(candidates)


def canonical_stabilizer_key(group: FiniteGroup, stabilizer: Iterable[int]) -> str:
    """Return the parent-domain-conjugacy key of an affine stabilizer."""
    selected = tuple(sorted(int(value) for value in stabilizer))
    if not selected:
        raise ValueError("a physical stabilizer must contain the identity")
    candidates = []
    for domain in range(group.order):
        candidates.append(
            ";".join(
                sorted(
                    group.element_keys[group.conjugate(element, domain)]
                    for element in selected
                )
            )
        )
    return min(candidates)


def enumerate_opd_classes(
    group: FiniteGroup,
    irrep: RealIrrep,
) -> tuple[OPDClass, ...]:
    """Enumerate maximal isotropy fixed spaces modulo parent-domain conjugacy.

    Distinct fixed spaces are constructed directly, without retaining a
    legacy full-subgroup execution branch.
    """
    representation = irrep.matrices
    if representation.shape[0] != group.order:
        raise ValueError("irrep and finite group orders do not match")
    if all(np.allclose(matrix, np.eye(irrep.dimension), atol=1e-9, rtol=1e-9) for matrix in representation):
        return ()
    projectors = enumerate_fixed_space_projectors(representation)
    fixed_dimensions = np.rint(
        np.trace(np.stack(projectors), axis1=1, axis2=2)
    ).astype(np.int64)
    classes: dict[str, OPDClass] = {}
    for projector, fixed_dimension_value in zip(projectors, fixed_dimensions):
        fixed_dimension = int(fixed_dimension_value)
        if fixed_dimension == 0:
            continue
        if not np.allclose(projector @ projector, projector, atol=1e-9, rtol=1e-9):
            raise RuntimeError("OPD Reynolds range did not form an idempotent projector")
        stabilizer = _pointwise_stabilizer(representation, projector)
        if not stabilizer:
            raise RuntimeError("a nonempty OPD fixed space lost the identity stabilizer")
        key = _domain_key(group, representation, projector, stabilizer)
        classes.setdefault(
            key,
            OPDClass(
                key,
                fixed_dimension,
                stabilizer,
                stabilizer_bitset(stabilizer, group_order=group.order),
                projector,
            ),
        )
    return tuple(sorted(classes.values(), key=lambda branch: branch.physical_key))
