"""Fail-closed provenance checks for A-v2 generated-state replay entries."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

import torch

from gaugeflow.vocabulary import CHEMICAL_ELEMENT_COUNT

GeneratedCarrierRole = Literal[
    "clean_clean",
    "generated_assignment",
    "generated_lattice",
    "generated_joint",
]

GeneratedStateSource = Literal[
    "clean",
    "sampled_composition",
    "generated_assignment",
    "generated_lattice",
    "generated_joint",
    "replay_cache",
]

_SOURCES = {
    "clean",
    "sampled_composition",
    "generated_assignment",
    "generated_lattice",
    "generated_joint",
    "replay_cache",
}

_ROLES = {
    "clean_clean",
    "generated_assignment",
    "generated_lattice",
    "generated_joint",
}

_ASSIGNMENT_SOURCES = {
    "clean_clean": {"clean"},
    "generated_assignment": {"generated_assignment", "replay_cache"},
    "generated_lattice": {"clean"},
    "generated_joint": {"generated_assignment", "generated_joint", "replay_cache"},
}

_LATTICE_SOURCES = {
    "clean_clean": {"clean"},
    "generated_assignment": {"clean"},
    "generated_lattice": {"generated_lattice", "replay_cache"},
    "generated_joint": {"generated_lattice", "generated_joint", "replay_cache"},
}


def _require_source(value: str, name: str) -> None:
    if value not in _SOURCES:
        raise ValueError(f"{name} has unknown generated-state source")


@dataclass(frozen=True)
class GeneratedStateReplayKey:
    """Identity that prevents silent reuse across checkpoints or samplers."""

    source_structure_id: str
    role: GeneratedCarrierRole
    base_checkpoint_sha256: str
    sampler_commit: str
    sampler_protocol_sha256: str
    refresh_id: int
    seed: int
    coordinate_time: float
    element_time: float
    lattice_time: float

    def validate(
        self,
        *,
        expected_base_checkpoint_sha256: str | None = None,
        expected_sampler_commit: str | None = None,
        expected_sampler_protocol_sha256: str | None = None,
    ) -> None:
        if not self.source_structure_id:
            raise ValueError("replay key requires a source structure id")
        if self.role not in _ROLES:
            raise ValueError("replay key has an unknown carrier role")
        for name, value in (
            ("base checkpoint", self.base_checkpoint_sha256),
            ("sampler commit", self.sampler_commit),
            ("sampler protocol", self.sampler_protocol_sha256),
        ):
            if not isinstance(value, str) or not value:
                raise ValueError(f"replay key has an empty {name} identity")
        if self.refresh_id < 0:
            raise ValueError("replay refresh id must be nonnegative")
        if not all(
            torch.isfinite(torch.tensor(value)).item()
            and 0.0 <= float(value) <= 1.0
            for value in (self.coordinate_time, self.element_time, self.lattice_time)
        ):
            raise ValueError("replay times must be finite values in [0,1]")
        if (
            expected_base_checkpoint_sha256 is not None
            and self.base_checkpoint_sha256 != expected_base_checkpoint_sha256
        ):
            raise ValueError("replay cache was generated by a different base checkpoint")
        if expected_sampler_commit is not None and self.sampler_commit != expected_sampler_commit:
            raise ValueError("replay cache was generated by a different sampler commit")
        if (
            expected_sampler_protocol_sha256 is not None
            and self.sampler_protocol_sha256 != expected_sampler_protocol_sha256
        ):
            raise ValueError("replay cache was generated by a different sampler protocol")


@dataclass(frozen=True)
class GeneratedStateReplayEntry:
    """One packed A-v2 carrier row with explicit clean/generated provenance."""

    key: GeneratedStateReplayKey
    source_split: str
    parent_or_flexible_carrier_id: str
    node_count: torch.Tensor
    composition_counts: torch.Tensor
    composition_source: GeneratedStateSource
    assignment_tokens: torch.Tensor
    assignment_source: GeneratedStateSource
    assignment_reveal_rank: torch.Tensor
    assignment_reveal_count: torch.Tensor
    lattice: torch.Tensor
    lattice_source: GeneratedStateSource
    lattice_log_volume: torch.Tensor
    lattice_log_shape: torch.Tensor
    fractional_coordinates: torch.Tensor
    coordinate_source: GeneratedStateSource

    def validate(
        self,
        *,
        vocabulary_size: int = CHEMICAL_ELEMENT_COUNT,
        mask_token: int = CHEMICAL_ELEMENT_COUNT,
        shape_projector: torch.Tensor | None = None,
        expected_base_checkpoint_sha256: str | None = None,
        expected_sampler_commit: str | None = None,
        expected_sampler_protocol_sha256: str | None = None,
    ) -> None:
        self.key.validate(
            expected_base_checkpoint_sha256=expected_base_checkpoint_sha256,
            expected_sampler_commit=expected_sampler_commit,
            expected_sampler_protocol_sha256=expected_sampler_protocol_sha256,
        )
        if not self.source_split:
            raise ValueError("replay entry requires a source split")
        if not self.parent_or_flexible_carrier_id:
            raise ValueError("replay entry requires a carrier id")
        role = self.key.role
        _require_source(self.composition_source, "composition")
        _require_source(self.assignment_source, "assignment")
        _require_source(self.lattice_source, "lattice")
        _require_source(self.coordinate_source, "coordinate")
        if self.assignment_source not in _ASSIGNMENT_SOURCES[role]:
            raise ValueError("assignment source is incompatible with replay role")
        if self.lattice_source not in _LATTICE_SOURCES[role]:
            raise ValueError("lattice source is incompatible with replay role")
        self._validate_counts(vocabulary_size=vocabulary_size)
        self._validate_assignment(vocabulary_size=vocabulary_size, mask_token=mask_token)
        self._validate_lattice(shape_projector=shape_projector)
        self._validate_coordinates()

    @property
    def graph_count(self) -> int:
        return int(self.node_count.numel())

    @property
    def node_total(self) -> int:
        return int(self.node_count.sum().item())

    def _validate_counts(self, *, vocabulary_size: int) -> None:
        graphs = self.graph_count
        if self.node_count.ndim != 1 or self.node_count.dtype != torch.long:
            raise ValueError("node count must be a rank-one int64 tensor")
        if graphs < 1 or bool((self.node_count < 1).any()):
            raise ValueError("node count must be positive for every graph")
        if (
            self.composition_counts.shape != (graphs, vocabulary_size)
            or self.composition_counts.dtype != torch.long
            or bool((self.composition_counts < 0).any())
        ):
            raise ValueError("composition counts must be nonnegative int64 [graphs,vocabulary]")
        if not torch.equal(self.composition_counts.sum(dim=1), self.node_count):
            raise ValueError("composition counts do not close on node count")

    def _validate_assignment(self, *, vocabulary_size: int, mask_token: int) -> None:
        nodes = self.node_total
        graphs = self.graph_count
        expected_batch = torch.repeat_interleave(
            torch.arange(graphs, device=self.node_count.device),
            self.node_count,
        ).to(self.assignment_tokens.device)
        if self.assignment_tokens.shape != (nodes,) or self.assignment_tokens.dtype != torch.long:
            raise ValueError("assignment tokens must provide one int64 value per node")
        if (
            self.assignment_reveal_rank.shape != (nodes,)
            or self.assignment_reveal_rank.dtype != torch.long
            or self.assignment_reveal_rank.device != self.assignment_tokens.device
        ):
            raise ValueError("assignment reveal rank must align with assignment tokens")
        if self.assignment_reveal_count.shape != (graphs,) or self.assignment_reveal_count.dtype != torch.long:
            raise ValueError("assignment reveal count must provide one int64 value per graph")
        if self.assignment_reveal_count.device != self.node_count.device:
            raise ValueError("assignment reveal count must share the node-count device")
        if bool((self.assignment_reveal_count < 0).any()) or bool(
            (self.assignment_reveal_count > self.node_count).any()
        ):
            raise ValueError("assignment reveal count must lie in [0,node_count]")
        allowed = (0 <= self.assignment_tokens) & (
            (self.assignment_tokens < vocabulary_size) | (self.assignment_tokens == mask_token)
        )
        if not bool(allowed.all()):
            raise ValueError("assignment contains an out-of-vocabulary token")
        for graph in range(graphs):
            selected = expected_batch == graph
            ranks = self.assignment_reveal_rank[selected]
            expected = torch.arange(int(self.node_count[graph]), device=ranks.device)
            if not torch.equal(ranks.sort().values, expected):
                raise ValueError("assignment reveal rank must be a per-graph permutation")
            reveal_count = int(self.assignment_reveal_count[graph])
            tokens = self.assignment_tokens[selected]
            visible = ranks < reveal_count
            if not bool((tokens[visible] != mask_token).all()):
                raise ValueError("revealed assignment sites cannot be masked")
            if not bool((tokens[~visible] == mask_token).all()):
                raise ValueError("unrevealed assignment sites must be masked")
        chemical = self.assignment_tokens != mask_token
        flat = expected_batch[chemical] * vocabulary_size + self.assignment_tokens[chemical]
        observed = torch.bincount(
            flat,
            minlength=graphs * vocabulary_size,
        ).reshape(graphs, vocabulary_size)
        if bool((observed > self.composition_counts.to(observed.device)).any()):
            raise ValueError("partial assignment exceeds declared composition counts")
        if torch.equal(self.assignment_reveal_count, self.node_count):
            if not torch.equal(observed.to(self.composition_counts.device), self.composition_counts):
                raise ValueError("complete assignment does not realize composition exactly")
        if self.assignment_source == "clean" and not torch.equal(self.assignment_reveal_count, self.node_count):
            raise ValueError("clean assignment source must expose the complete clean assignment")

    def _validate_lattice(self, *, shape_projector: torch.Tensor | None) -> None:
        graphs = self.graph_count
        if self.lattice.shape != (graphs, 3, 3) or not torch.isfinite(self.lattice).all():
            raise ValueError("lattice must be finite [graphs,3,3]")
        if bool((torch.linalg.det(self.lattice) <= 0).any()):
            raise ValueError("lattice must have positive determinant")
        if self.lattice_log_volume.shape != (graphs,) or not torch.isfinite(self.lattice_log_volume).all():
            raise ValueError("lattice log-volume must be finite [graphs]")
        if self.lattice_log_shape.shape != (graphs, 6) or not torch.isfinite(self.lattice_log_shape).all():
            raise ValueError("lattice log-shape must be finite [graphs,6]")
        if shape_projector is not None:
            if shape_projector.shape != (graphs, 6, 6):
                raise ValueError("shape projector must be [graphs,6,6]")
            projected = torch.einsum("bij,bj->bi", shape_projector.to(self.lattice_log_shape), self.lattice_log_shape)
            if not torch.allclose(projected, self.lattice_log_shape, atol=2.0e-6, rtol=2.0e-6):
                raise ValueError("lattice log-shape is outside the declared shape subspace")

    def _validate_coordinates(self) -> None:
        nodes = self.node_total
        if self.fractional_coordinates.shape != (nodes, 3):
            raise ValueError("fractional coordinates must be [nodes,3]")
        if not torch.isfinite(self.fractional_coordinates).all():
            raise ValueError("fractional coordinates must be finite")


def validate_no_forbidden_source_ids(
    entries: list[GeneratedStateReplayEntry],
    forbidden_source_ids: set[str],
) -> None:
    """Reject replay panels that overlap a held-out evaluation/test universe."""

    overlap = sorted({entry.key.source_structure_id for entry in entries} & forbidden_source_ids)
    if overlap:
        preview = ", ".join(overlap[:5])
        raise ValueError(f"generated-state replay overlaps forbidden source ids: {preview}")
