"""Fail-closed provenance checks for A-v2 generated-state replay entries."""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import torch

from gaugeflow.vocabulary import CHEMICAL_ELEMENT_COUNT

GeneratedCarrierRole = Literal[
    "clean_clean",
    "generated_assignment",
    "generated_lattice",
    "generated_joint",
]

GeneratedStateSource = Literal[
    "clean",
    "sampled_composition",
    "generated_assignment",
    "generated_lattice",
    "generated_joint",
    "replay_cache",
]

_SOURCES = {
    "clean",
    "sampled_composition",
    "generated_assignment",
    "generated_lattice",
    "generated_joint",
    "replay_cache",
}

_ROLES = {
    "clean_clean",
    "generated_assignment",
    "generated_lattice",
    "generated_joint",
}

_ASSIGNMENT_SOURCES = {
    "clean_clean": {"clean"},
    "generated_assignment": {"generated_assignment", "replay_cache"},
    "generated_lattice": {"clean"},
    "generated_joint": {"generated_assignment", "generated_joint", "replay_cache"},
}

_LATTICE_SOURCES = {
    "clean_clean": {"clean"},
    "generated_assignment": {"clean"},
    "generated_lattice": {"generated_lattice", "replay_cache"},
    "generated_joint": {"generated_lattice", "generated_joint", "replay_cache"},
}

_CACHE_MANIFEST_FILENAME = "generated_state_replay_manifest.json"
_CACHE_PAYLOAD_FILENAME = "generated_state_replay_payload.pt"
_TENSOR_PAYLOAD_KEYS = {
    "node_count",
    "composition_counts",
    "assignment_tokens",
    "assignment_reveal_rank",
    "assignment_reveal_count",
    "lattice",
    "lattice_log_volume",
    "lattice_log_shape",
    "fractional_coordinates",
}


def _require_source(value: str, name: str) -> None:
    if value not in _SOURCES:
        raise ValueError(f"{name} has unknown generated-state source")


@dataclass(frozen=True)
class GeneratedStateReplayKey:
    """Identity that prevents silent reuse across checkpoints or samplers."""

    source_structure_id: str
    role: GeneratedCarrierRole
    base_checkpoint_sha256: str
    sampler_commit: str
    sampler_protocol_sha256: str
    refresh_id: int
    seed: int
    coordinate_time: float
    element_time: float
    lattice_time: float

    def validate(
        self,
        *,
        expected_base_checkpoint_sha256: str | None = None,
        expected_sampler_commit: str | None = None,
        expected_sampler_protocol_sha256: str | None = None,
    ) -> None:
        if not self.source_structure_id:
            raise ValueError("replay key requires a source structure id")
        if self.role not in _ROLES:
            raise ValueError("replay key has an unknown carrier role")
        for name, value in (
            ("base checkpoint", self.base_checkpoint_sha256),
            ("sampler commit", self.sampler_commit),
            ("sampler protocol", self.sampler_protocol_sha256),
        ):
            if not isinstance(value, str) or not value:
                raise ValueError(f"replay key has an empty {name} identity")
        if self.refresh_id < 0:
            raise ValueError("replay refresh id must be nonnegative")
        if not all(
            torch.isfinite(torch.tensor(value)).item()
            and 0.0 <= float(value) <= 1.0
            for value in (self.coordinate_time, self.element_time, self.lattice_time)
        ):
            raise ValueError("replay times must be finite values in [0,1]")
        if (
            expected_base_checkpoint_sha256 is not None
            and self.base_checkpoint_sha256 != expected_base_checkpoint_sha256
        ):
            raise ValueError("replay cache was generated by a different base checkpoint")
        if expected_sampler_commit is not None and self.sampler_commit != expected_sampler_commit:
            raise ValueError("replay cache was generated by a different sampler commit")
        if (
            expected_sampler_protocol_sha256 is not None
            and self.sampler_protocol_sha256 != expected_sampler_protocol_sha256
        ):
                raise ValueError("replay cache was generated by a different sampler protocol")

    def to_json_object(self) -> dict[str, object]:
        return {
            "source_structure_id": self.source_structure_id,
            "role": self.role,
            "base_checkpoint_sha256": self.base_checkpoint_sha256,
            "sampler_commit": self.sampler_commit,
            "sampler_protocol_sha256": self.sampler_protocol_sha256,
            "refresh_id": self.refresh_id,
            "seed": self.seed,
            "coordinate_time": self.coordinate_time,
            "element_time": self.element_time,
            "lattice_time": self.lattice_time,
        }

    @staticmethod
    def from_json_object(value: dict[str, object]) -> GeneratedStateReplayKey:
        role = str(value["role"])
        if role not in _ROLES:
            raise ValueError("replay key has an unknown carrier role")
        key = GeneratedStateReplayKey(
            source_structure_id=str(value["source_structure_id"]),
            role=role,  # type: ignore[arg-type]
            base_checkpoint_sha256=str(value["base_checkpoint_sha256"]),
            sampler_commit=str(value["sampler_commit"]),
            sampler_protocol_sha256=str(value["sampler_protocol_sha256"]),
            refresh_id=_require_int(value["refresh_id"], "refresh id"),
            seed=_require_int(value["seed"], "seed"),
            coordinate_time=_require_float(value["coordinate_time"], "coordinate time"),
            element_time=_require_float(value["element_time"], "element time"),
            lattice_time=_require_float(value["lattice_time"], "lattice time"),
        )
        key.validate()
        return key

    def cache_identity_tuple(self) -> tuple[object, ...]:
        return (
            self.source_structure_id,
            self.role,
            self.base_checkpoint_sha256,
            self.sampler_commit,
            self.sampler_protocol_sha256,
            self.refresh_id,
            self.seed,
            self.coordinate_time,
            self.element_time,
            self.lattice_time,
        )


@dataclass(frozen=True)
class GeneratedStateReplayEntry:
    """One packed A-v2 carrier row with explicit clean/generated provenance."""

    key: GeneratedStateReplayKey
    source_split: str
    parent_or_flexible_carrier_id: str
    node_count: torch.Tensor
    composition_counts: torch.Tensor
    composition_source: GeneratedStateSource
    assignment_tokens: torch.Tensor
    assignment_source: GeneratedStateSource
    assignment_reveal_rank: torch.Tensor
    assignment_reveal_count: torch.Tensor
    lattice: torch.Tensor
    lattice_source: GeneratedStateSource
    lattice_log_volume: torch.Tensor
    lattice_log_shape: torch.Tensor
    fractional_coordinates: torch.Tensor
    coordinate_source: GeneratedStateSource

    def validate(
        self,
        *,
        vocabulary_size: int = CHEMICAL_ELEMENT_COUNT,
        mask_token: int = CHEMICAL_ELEMENT_COUNT,
        shape_projector: torch.Tensor | None = None,
        expected_base_checkpoint_sha256: str | None = None,
        expected_sampler_commit: str | None = None,
        expected_sampler_protocol_sha256: str | None = None,
    ) -> None:
        self.key.validate(
            expected_base_checkpoint_sha256=expected_base_checkpoint_sha256,
            expected_sampler_commit=expected_sampler_commit,
            expected_sampler_protocol_sha256=expected_sampler_protocol_sha256,
        )
        if not self.source_split:
            raise ValueError("replay entry requires a source split")
        if not self.parent_or_flexible_carrier_id:
            raise ValueError("replay entry requires a carrier id")
        role = self.key.role
        _require_source(self.composition_source, "composition")
        _require_source(self.assignment_source, "assignment")
        _require_source(self.lattice_source, "lattice")
        _require_source(self.coordinate_source, "coordinate")
        if self.assignment_source not in _ASSIGNMENT_SOURCES[role]:
            raise ValueError("assignment source is incompatible with replay role")
        if self.lattice_source not in _LATTICE_SOURCES[role]:
            raise ValueError("lattice source is incompatible with replay role")
        self._validate_counts(vocabulary_size=vocabulary_size)
        self._validate_assignment(vocabulary_size=vocabulary_size, mask_token=mask_token)
        self._validate_lattice(shape_projector=shape_projector)
        self._validate_coordinates()

    @property
    def graph_count(self) -> int:
        return int(self.node_count.numel())

    @property
    def node_total(self) -> int:
        return int(self.node_count.sum().item())

    def _validate_counts(self, *, vocabulary_size: int) -> None:
        graphs = self.graph_count
        if self.node_count.ndim != 1 or self.node_count.dtype != torch.long:
            raise ValueError("node count must be a rank-one int64 tensor")
        if graphs < 1 or bool((self.node_count < 1).any()):
            raise ValueError("node count must be positive for every graph")
        if (
            self.composition_counts.shape != (graphs, vocabulary_size)
            or self.composition_counts.dtype != torch.long
            or bool((self.composition_counts < 0).any())
        ):
            raise ValueError("composition counts must be nonnegative int64 [graphs,vocabulary]")
        if not torch.equal(self.composition_counts.sum(dim=1), self.node_count):
            raise ValueError("composition counts do not close on node count")

    def _validate_assignment(self, *, vocabulary_size: int, mask_token: int) -> None:
        nodes = self.node_total
        graphs = self.graph_count
        expected_batch = torch.repeat_interleave(
            torch.arange(graphs, device=self.node_count.device),
            self.node_count,
        ).to(self.assignment_tokens.device)
        if self.assignment_tokens.shape != (nodes,) or self.assignment_tokens.dtype != torch.long:
            raise ValueError("assignment tokens must provide one int64 value per node")
        if (
            self.assignment_reveal_rank.shape != (nodes,)
            or self.assignment_reveal_rank.dtype != torch.long
            or self.assignment_reveal_rank.device != self.assignment_tokens.device
        ):
            raise ValueError("assignment reveal rank must align with assignment tokens")
        if self.assignment_reveal_count.shape != (graphs,) or self.assignment_reveal_count.dtype != torch.long:
            raise ValueError("assignment reveal count must provide one int64 value per graph")
        if self.assignment_reveal_count.device != self.node_count.device:
            raise ValueError("assignment reveal count must share the node-count device")
        if bool((self.assignment_reveal_count < 0).any()) or bool(
            (self.assignment_reveal_count > self.node_count).any()
        ):
            raise ValueError("assignment reveal count must lie in [0,node_count]")
        allowed = (0 <= self.assignment_tokens) & (
            (self.assignment_tokens < vocabulary_size) | (self.assignment_tokens == mask_token)
        )
        if not bool(allowed.all()):
            raise ValueError("assignment contains an out-of-vocabulary token")
        for graph in range(graphs):
            selected = expected_batch == graph
            ranks = self.assignment_reveal_rank[selected]
            expected = torch.arange(int(self.node_count[graph]), device=ranks.device)
            if not torch.equal(ranks.sort().values, expected):
                raise ValueError("assignment reveal rank must be a per-graph permutation")
            reveal_count = int(self.assignment_reveal_count[graph])
            tokens = self.assignment_tokens[selected]
            visible = ranks < reveal_count
            if not bool((tokens[visible] != mask_token).all()):
                raise ValueError("revealed assignment sites cannot be masked")
            if not bool((tokens[~visible] == mask_token).all()):
                raise ValueError("unrevealed assignment sites must be masked")
        chemical = self.assignment_tokens != mask_token
        flat = expected_batch[chemical] * vocabulary_size + self.assignment_tokens[chemical]
        observed = torch.bincount(
            flat,
            minlength=graphs * vocabulary_size,
        ).reshape(graphs, vocabulary_size)
        if bool((observed > self.composition_counts.to(observed.device)).any()):
            raise ValueError("partial assignment exceeds declared composition counts")
        if torch.equal(self.assignment_reveal_count, self.node_count):
            if not torch.equal(observed.to(self.composition_counts.device), self.composition_counts):
                raise ValueError("complete assignment does not realize composition exactly")
        if self.assignment_source == "clean" and not torch.equal(self.assignment_reveal_count, self.node_count):
            raise ValueError("clean assignment source must expose the complete clean assignment")

    def _validate_lattice(self, *, shape_projector: torch.Tensor | None) -> None:
        graphs = self.graph_count
        if self.lattice.shape != (graphs, 3, 3) or not torch.isfinite(self.lattice).all():
            raise ValueError("lattice must be finite [graphs,3,3]")
        if bool((torch.linalg.det(self.lattice) <= 0).any()):
            raise ValueError("lattice must have positive determinant")
        if self.lattice_log_volume.shape != (graphs,) or not torch.isfinite(self.lattice_log_volume).all():
            raise ValueError("lattice log-volume must be finite [graphs]")
        if self.lattice_log_shape.shape != (graphs, 6) or not torch.isfinite(self.lattice_log_shape).all():
            raise ValueError("lattice log-shape must be finite [graphs,6]")
        if shape_projector is not None:
            if shape_projector.shape != (graphs, 6, 6):
                raise ValueError("shape projector must be [graphs,6,6]")
            projected = torch.einsum("bij,bj->bi", shape_projector.to(self.lattice_log_shape), self.lattice_log_shape)
            if not torch.allclose(projected, self.lattice_log_shape, atol=2.0e-6, rtol=2.0e-6):
                raise ValueError("lattice log-shape is outside the declared shape subspace")

    def _validate_coordinates(self) -> None:
        nodes = self.node_total
        if self.fractional_coordinates.shape != (nodes, 3):
            raise ValueError("fractional coordinates must be [nodes,3]")
        if not torch.isfinite(self.fractional_coordinates).all():
            raise ValueError("fractional coordinates must be finite")


def _canonical_json_sha256(value: object) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _tensor_sha256(tensor: torch.Tensor) -> str:
    materialized = tensor.detach().cpu().contiguous()
    array = materialized.numpy()
    digest = hashlib.sha256()
    metadata = {
        "dtype": str(materialized.dtype),
        "shape": list(materialized.shape),
    }
    digest.update(json.dumps(metadata, sort_keys=True, separators=(",", ":")).encode("utf-8"))
    digest.update(array.tobytes(order="C"))
    return digest.hexdigest()


def _require_string(value: object, name: str) -> str:
    if not isinstance(value, str) or not value:
        raise ValueError(f"{name} must be a nonempty string")
    return value


def _require_int(value: object, name: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"{name} must be an integer")
    return int(value)


def _require_float(value: object, name: str) -> float:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise ValueError(f"{name} must be numeric")
    return float(value)


def _require_string_dict(value: object, name: str) -> dict[str, str]:
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    result: dict[str, str] = {}
    for key, item in value.items():
        if not isinstance(key, str) or not isinstance(item, str) or not item:
            raise ValueError(f"{name} must map strings to nonempty strings")
        result[key] = item
    return result


def _require_int_list(value: object, name: str) -> list[int]:
    if not isinstance(value, list) or not all(isinstance(item, int) for item in value):
        raise ValueError(f"{name} must be a list of integers")
    return [int(item) for item in value]


def _require_tensor_dict(value: object, name: str) -> dict[str, torch.Tensor]:
    if not isinstance(value, dict):
        raise ValueError(f"{name} must be an object")
    result: dict[str, torch.Tensor] = {}
    for key, item in value.items():
        if not isinstance(key, str) or not isinstance(item, torch.Tensor):
            raise ValueError(f"{name} must map strings to tensors")
        result[key] = item
    return result


@dataclass(frozen=True)
class GeneratedStateReplayManifestRow:
    """Small manifest row that binds one replay entry to tensor payload hashes."""

    key: GeneratedStateReplayKey
    source_split: str
    parent_or_flexible_carrier_id: str
    node_count: tuple[int, ...]
    composition_source: GeneratedStateSource
    assignment_source: GeneratedStateSource
    lattice_source: GeneratedStateSource
    coordinate_source: GeneratedStateSource
    tensor_sha256: dict[str, str]

    @staticmethod
    def from_entry(entry: GeneratedStateReplayEntry) -> GeneratedStateReplayManifestRow:
        entry.validate()
        return GeneratedStateReplayManifestRow(
            key=entry.key,
            source_split=entry.source_split,
            parent_or_flexible_carrier_id=entry.parent_or_flexible_carrier_id,
            node_count=tuple(int(value) for value in entry.node_count.detach().cpu().tolist()),
            composition_source=entry.composition_source,
            assignment_source=entry.assignment_source,
            lattice_source=entry.lattice_source,
            coordinate_source=entry.coordinate_source,
            tensor_sha256={
                "node_count": _tensor_sha256(entry.node_count),
                "composition_counts": _tensor_sha256(entry.composition_counts),
                "assignment_tokens": _tensor_sha256(entry.assignment_tokens),
                "assignment_reveal_rank": _tensor_sha256(entry.assignment_reveal_rank),
                "assignment_reveal_count": _tensor_sha256(entry.assignment_reveal_count),
                "lattice": _tensor_sha256(entry.lattice),
                "lattice_log_volume": _tensor_sha256(entry.lattice_log_volume),
                "lattice_log_shape": _tensor_sha256(entry.lattice_log_shape),
                "fractional_coordinates": _tensor_sha256(entry.fractional_coordinates),
            },
        )

    def validate_against_entry(self, entry: GeneratedStateReplayEntry) -> None:
        expected = GeneratedStateReplayManifestRow.from_entry(entry)
        if self.to_json_object() != expected.to_json_object():
            raise ValueError("replay manifest row does not match replay entry payload")

    def to_json_object(self) -> dict[str, object]:
        return {
            "key": self.key.to_json_object(),
            "source_split": self.source_split,
            "parent_or_flexible_carrier_id": self.parent_or_flexible_carrier_id,
            "node_count": list(self.node_count),
            "composition_source": self.composition_source,
            "assignment_source": self.assignment_source,
            "lattice_source": self.lattice_source,
            "coordinate_source": self.coordinate_source,
            "tensor_sha256": dict(sorted(self.tensor_sha256.items())),
        }

    @staticmethod
    def from_json_object(value: dict[str, object]) -> GeneratedStateReplayManifestRow:
        key_value = value.get("key")
        if not isinstance(key_value, dict):
            raise ValueError("replay manifest row requires a key object")
        composition_source = _require_string(value.get("composition_source"), "composition source")
        assignment_source = _require_string(value.get("assignment_source"), "assignment source")
        lattice_source = _require_string(value.get("lattice_source"), "lattice source")
        coordinate_source = _require_string(value.get("coordinate_source"), "coordinate source")
        for source_name, source in (
            ("composition", composition_source),
            ("assignment", assignment_source),
            ("lattice", lattice_source),
            ("coordinate", coordinate_source),
        ):
            _require_source(source, source_name)
        row = GeneratedStateReplayManifestRow(
            key=GeneratedStateReplayKey.from_json_object(key_value),
            source_split=_require_string(value.get("source_split"), "source split"),
            parent_or_flexible_carrier_id=_require_string(
                value.get("parent_or_flexible_carrier_id"),
                "carrier id",
            ),
            node_count=tuple(_require_int_list(value.get("node_count"), "node count")),
            composition_source=composition_source,  # type: ignore[arg-type]
            assignment_source=assignment_source,  # type: ignore[arg-type]
            lattice_source=lattice_source,  # type: ignore[arg-type]
            coordinate_source=coordinate_source,  # type: ignore[arg-type]
            tensor_sha256=_require_string_dict(value.get("tensor_sha256"), "tensor sha256"),
        )
        row.validate_metadata()
        return row

    def validate_metadata(self) -> None:
        self.key.validate()
        if not self.source_split:
            raise ValueError("replay manifest row requires a source split")
        if not self.parent_or_flexible_carrier_id:
            raise ValueError("replay manifest row requires a carrier id")
        if not self.node_count or any(count < 1 for count in self.node_count):
            raise ValueError("replay manifest row node counts must be positive")
        _require_source(self.composition_source, "composition")
        _require_source(self.assignment_source, "assignment")
        _require_source(self.lattice_source, "lattice")
        _require_source(self.coordinate_source, "coordinate")
        if self.assignment_source not in _ASSIGNMENT_SOURCES[self.key.role]:
            raise ValueError("assignment source is incompatible with replay role")
        if self.lattice_source not in _LATTICE_SOURCES[self.key.role]:
            raise ValueError("lattice source is incompatible with replay role")
        if set(self.tensor_sha256) != _TENSOR_PAYLOAD_KEYS:
            raise ValueError("replay manifest row has incomplete tensor payload hashes")


@dataclass(frozen=True)
class GeneratedStateReplayManifest:
    """Deterministic replay-cache manifest with checkpoint/sampler provenance."""

    rows: tuple[GeneratedStateReplayManifestRow, ...]
    format_version: int = 1

    @staticmethod
    def from_entries(entries: list[GeneratedStateReplayEntry]) -> GeneratedStateReplayManifest:
        return GeneratedStateReplayManifest(
            rows=tuple(GeneratedStateReplayManifestRow.from_entry(entry) for entry in entries),
        )

    def validate(
        self,
        *,
        expected_base_checkpoint_sha256: str | None = None,
        expected_sampler_commit: str | None = None,
        expected_sampler_protocol_sha256: str | None = None,
        forbidden_source_ids: set[str] | None = None,
    ) -> None:
        if self.format_version != 1:
            raise ValueError("unsupported generated-state replay manifest version")
        if not self.rows:
            raise ValueError("generated-state replay manifest is empty")
        seen: set[tuple[object, ...]] = set()
        source_ids: set[str] = set()
        for row in self.rows:
            row.validate_metadata()
            row.key.validate(
                expected_base_checkpoint_sha256=expected_base_checkpoint_sha256,
                expected_sampler_commit=expected_sampler_commit,
                expected_sampler_protocol_sha256=expected_sampler_protocol_sha256,
            )
            identity = row.key.cache_identity_tuple()
            if identity in seen:
                raise ValueError("generated-state replay manifest contains duplicate cache keys")
            seen.add(identity)
            source_ids.add(row.key.source_structure_id)
        if forbidden_source_ids is not None:
            overlap = sorted(source_ids & forbidden_source_ids)
            if overlap:
                preview = ", ".join(overlap[:5])
                raise ValueError(f"generated-state replay manifest overlaps forbidden source ids: {preview}")

    def validate_against_entries(self, entries: list[GeneratedStateReplayEntry]) -> None:
        if len(entries) != len(self.rows):
            raise ValueError("replay manifest entry count does not match payload count")
        for row, entry in zip(self.rows, entries, strict=True):
            row.validate_against_entry(entry)

    def to_json_object(self) -> dict[str, object]:
        return {
            "format_version": self.format_version,
            "rows": [row.to_json_object() for row in self.rows],
        }

    @staticmethod
    def from_json_object(value: dict[str, object]) -> GeneratedStateReplayManifest:
        rows_value = value.get("rows")
        if not isinstance(rows_value, list):
            raise ValueError("generated-state replay manifest requires a rows list")
        manifest = GeneratedStateReplayManifest(
            format_version=_require_int(value.get("format_version"), "format version"),
            rows=tuple(
                GeneratedStateReplayManifestRow.from_json_object(row)
                for row in rows_value
                if isinstance(row, dict)
            ),
        )
        if len(manifest.rows) != len(rows_value):
            raise ValueError("generated-state replay manifest rows must be objects")
        manifest.validate()
        return manifest

    def canonical_sha256(self) -> str:
        return _canonical_json_sha256(self.to_json_object())


def write_generated_state_replay_manifest(
    path: Path,
    manifest: GeneratedStateReplayManifest,
) -> str:
    """Write a deterministic JSON manifest and return its canonical SHA-256."""

    manifest.validate()
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = manifest.to_json_object()
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return manifest.canonical_sha256()


def load_generated_state_replay_manifest(path: Path) -> GeneratedStateReplayManifest:
    value: Any = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError("generated-state replay manifest must be a JSON object")
    return GeneratedStateReplayManifest.from_json_object(value)


def _entry_to_payload(entry: GeneratedStateReplayEntry) -> dict[str, object]:
    entry.validate()
    return {
        "key": entry.key.to_json_object(),
        "source_split": entry.source_split,
        "parent_or_flexible_carrier_id": entry.parent_or_flexible_carrier_id,
        "composition_source": entry.composition_source,
        "assignment_source": entry.assignment_source,
        "lattice_source": entry.lattice_source,
        "coordinate_source": entry.coordinate_source,
        "tensors": {
            "node_count": entry.node_count.detach().cpu(),
            "composition_counts": entry.composition_counts.detach().cpu(),
            "assignment_tokens": entry.assignment_tokens.detach().cpu(),
            "assignment_reveal_rank": entry.assignment_reveal_rank.detach().cpu(),
            "assignment_reveal_count": entry.assignment_reveal_count.detach().cpu(),
            "lattice": entry.lattice.detach().cpu(),
            "lattice_log_volume": entry.lattice_log_volume.detach().cpu(),
            "lattice_log_shape": entry.lattice_log_shape.detach().cpu(),
            "fractional_coordinates": entry.fractional_coordinates.detach().cpu(),
        },
    }


def _entry_from_payload(value: object) -> GeneratedStateReplayEntry:
    if not isinstance(value, dict):
        raise ValueError("generated-state replay payload entry must be an object")
    key_value = value.get("key")
    if not isinstance(key_value, dict):
        raise ValueError("generated-state replay payload entry requires a key object")
    tensors = _require_tensor_dict(value.get("tensors"), "replay payload tensors")
    if set(tensors) != _TENSOR_PAYLOAD_KEYS:
        raise ValueError("generated-state replay payload has incomplete tensors")
    composition_source = _require_string(value.get("composition_source"), "composition source")
    assignment_source = _require_string(value.get("assignment_source"), "assignment source")
    lattice_source = _require_string(value.get("lattice_source"), "lattice source")
    coordinate_source = _require_string(value.get("coordinate_source"), "coordinate source")
    for source_name, source in (
        ("composition", composition_source),
        ("assignment", assignment_source),
        ("lattice", lattice_source),
        ("coordinate", coordinate_source),
    ):
        _require_source(source, source_name)
    entry = GeneratedStateReplayEntry(
        key=GeneratedStateReplayKey.from_json_object(key_value),
        source_split=_require_string(value.get("source_split"), "source split"),
        parent_or_flexible_carrier_id=_require_string(
            value.get("parent_or_flexible_carrier_id"),
            "carrier id",
        ),
        node_count=tensors["node_count"],
        composition_counts=tensors["composition_counts"],
        composition_source=composition_source,  # type: ignore[arg-type]
        assignment_tokens=tensors["assignment_tokens"],
        assignment_source=assignment_source,  # type: ignore[arg-type]
        assignment_reveal_rank=tensors["assignment_reveal_rank"],
        assignment_reveal_count=tensors["assignment_reveal_count"],
        lattice=tensors["lattice"],
        lattice_source=lattice_source,  # type: ignore[arg-type]
        lattice_log_volume=tensors["lattice_log_volume"],
        lattice_log_shape=tensors["lattice_log_shape"],
        fractional_coordinates=tensors["fractional_coordinates"],
        coordinate_source=coordinate_source,  # type: ignore[arg-type]
    )
    entry.validate()
    return entry


def write_generated_state_replay_cache(
    directory: Path,
    entries: list[GeneratedStateReplayEntry],
) -> str:
    """Write replay payload tensors plus manifest, returning the manifest hash."""

    manifest = GeneratedStateReplayManifest.from_entries(entries)
    manifest.validate_against_entries(entries)
    directory.mkdir(parents=True, exist_ok=True)
    payload = {
        "format_version": 1,
        "entries": [_entry_to_payload(entry) for entry in entries],
    }
    torch.save(payload, directory / _CACHE_PAYLOAD_FILENAME)
    return write_generated_state_replay_manifest(directory / _CACHE_MANIFEST_FILENAME, manifest)


def load_generated_state_replay_cache(
    directory: Path,
    *,
    expected_base_checkpoint_sha256: str | None = None,
    expected_sampler_commit: str | None = None,
    expected_sampler_protocol_sha256: str | None = None,
    forbidden_source_ids: set[str] | None = None,
) -> tuple[list[GeneratedStateReplayEntry], GeneratedStateReplayManifest]:
    """Load a replay cache and reject stale or tampered payloads."""

    manifest = load_generated_state_replay_manifest(directory / _CACHE_MANIFEST_FILENAME)
    manifest.validate(
        expected_base_checkpoint_sha256=expected_base_checkpoint_sha256,
        expected_sampler_commit=expected_sampler_commit,
        expected_sampler_protocol_sha256=expected_sampler_protocol_sha256,
        forbidden_source_ids=forbidden_source_ids,
    )
    payload: Any = torch.load(directory / _CACHE_PAYLOAD_FILENAME, map_location="cpu", weights_only=True)
    if not isinstance(payload, dict):
        raise ValueError("generated-state replay payload must be an object")
    if payload.get("format_version") != 1:
        raise ValueError("unsupported generated-state replay payload version")
    entries_value = payload.get("entries")
    if not isinstance(entries_value, list):
        raise ValueError("generated-state replay payload requires an entries list")
    entries = [_entry_from_payload(item) for item in entries_value]
    manifest.validate_against_entries(entries)
    return entries, manifest


def validate_no_forbidden_source_ids(
    entries: list[GeneratedStateReplayEntry],
    forbidden_source_ids: set[str],
) -> None:
    """Reject replay panels that overlap a held-out evaluation/test universe."""

    overlap = sorted({entry.key.source_structure_id for entry in entries} & forbidden_source_ids)
    if overlap:
        preview = ", ".join(overlap[:5])
        raise ValueError(f"generated-state replay overlaps forbidden source ids: {preview}")
