"""Discrete atom-type flow matching on an absorbing mask probability path.

The crystal's atomic species are categorical variables, not Euclidean logits.
This module implements the simple absorbing path used by discrete flow
matching: a token is the endpoint element with probability ``t`` and a
non-chemical mask token otherwise.  The model learns the endpoint posterior
and the sampler uses the path's exact masked-to-element jump probability.

The mask index is internal to the generator and is excluded from every decoded
crystal.  Coordinates and lattice are supplied only to make a type-only
substrate audit well defined; they are not generated by this matcher.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch
import torch.nn.functional as F

from .flow import CrystalFlowState
from .manifold import lattice_to_log_vector
from .vocabulary import CHEMICAL_ELEMENT_COUNT


@dataclass(frozen=True)
class DiscreteSamplingNoise:
    """Fixed uniforms used to make two conditional samples counterfactuals."""

    reveal_uniform: torch.Tensor
    categorical_uniform: torch.Tensor


class AbsorbingDiscreteTypeFlowMatcher:
    """Endpoint-posterior DFM for atom types with an absorbing mask source.

    For a target element ``y`` and mask token ``m``, the conditional path is

    ``p_t(x | y) = t delta_y(x) + (1-t) delta_m(x)``.

    A masked token therefore jumps during ``[t, t + dt]`` with probability
    ``dt / (1-t)``.  Its destination is sampled from the learned posterior
    ``p_theta(y | x_t, t, c)``.  With the exact posterior this sampler has the
    stated path marginals and ends at the data distribution without a final
    continuous relaxation or an argmax decoder.
    """

    def __init__(
        self,
        atom_types: int = CHEMICAL_ELEMENT_COUNT,
        training_time_distribution: str = "uniform",
    ):
        if atom_types < 2:
            raise ValueError("atom_types must contain at least two chemical elements")
        if training_time_distribution not in {"uniform", "beta_half_source"}:
            raise ValueError("training_time_distribution must be 'uniform' or 'beta_half_source'")
        self.atom_types = atom_types
        self.mask_index = atom_types
        self.state_dim = atom_types + 1
        self.training_time_distribution = training_time_distribution

    def training_time(self, graphs: int, device: torch.device) -> torch.Tensor:
        """Sample a positive-density DFM loss weighting over path time.

        ``beta_half_source`` is Beta(1/2, 1), implemented as ``U**2``.  It
        leaves the pointwise endpoint-posterior optimum unchanged for all
        ``t>0`` while placing twice as much expected mass on the all-mask
        source region that sampling must start from.
        """
        value = torch.rand((graphs,), device=device)
        return value.square() if self.training_time_distribution == "beta_half_source" else value

    def _state(self, tokens: torch.Tensor, batch) -> CrystalFlowState:
        if tokens.ndim != 1 or tokens.numel() != batch.atom_types.numel():
            raise ValueError("one discrete token is required for every atom")
        if tokens.min() < 0 or tokens.max() > self.mask_index:
            raise ValueError("discrete state contains an out-of-vocabulary token")
        return CrystalFlowState(
            type_state=F.one_hot(tokens, self.state_dim).to(dtype=batch.frac_coords.dtype),
            frac_coords=batch.frac_coords,
            lattice_log=lattice_to_log_vector(batch.lattice),
        )

    def mask_state(self, batch) -> CrystalFlowState:
        """Return the exact source state: every atom is the non-chemical mask."""
        tokens = torch.full_like(batch.atom_types, self.mask_index)
        return self._state(tokens, batch)

    def corrupt(self, batch, time: torch.Tensor) -> tuple[CrystalFlowState, torch.Tensor]:
        """Draw ``x_t`` from the absorbing conditional probability path."""
        if time.shape != (batch.num_graphs,):
            raise ValueError("time must contain one value per graph")
        if not bool(((time >= 0) & (time <= 1)).all()):
            raise ValueError("time must lie in [0, 1]")
        revealed = torch.rand_like(batch.frac_coords[:, 0]) < time[batch.batch]
        tokens = torch.where(revealed, batch.atom_types, torch.full_like(batch.atom_types, self.mask_index))
        return self._state(tokens, batch), revealed

    def posterior_logits(self, model, state: CrystalFlowState, batch, time: torch.Tensor) -> torch.Tensor:
        """Return chemical-element logits; the mask is never a decoded target."""
        logits = model(
            state.type_state, state.frac_coords, state.lattice_log, batch.batch, time,
            batch.piezo_irreps, batch.condition_present, getattr(batch, "condition_orbit", None),
        )[0]
        if logits.shape != (batch.atom_types.numel(), self.state_dim):
            raise ValueError(
                f"discrete model must emit [{batch.atom_types.numel()}, {self.state_dim}] logits, got {tuple(logits.shape)}"
            )
        return logits[:, : self.atom_types]

    def loss(self, model, batch) -> dict[str, torch.Tensor]:
        """The standard endpoint-posterior cross entropy for the DFM path."""
        time = self.training_time(batch.num_graphs, batch.batch.device)
        state, revealed = self.corrupt(batch, time)
        logits = self.posterior_logits(model, state, batch, time)
        per_atom = F.cross_entropy(logits, batch.atom_types, reduction="none")
        masked = ~revealed
        zero = per_atom.new_zeros(())
        return {
            "loss": per_atom.mean(),
            "endpoint_nll": per_atom.mean(),
            "masked_endpoint_nll": per_atom[masked].mean() if bool(masked.any()) else zero,
            "revealed_copy_nll": per_atom[revealed].mean() if bool(revealed.any()) else zero,
            "masked_fraction": masked.float().mean(),
            "masked_top1_accuracy": (
                (logits[masked].argmax(dim=-1) == batch.atom_types[masked]).float().mean()
                if bool(masked.any()) else zero
            ),
        }

    def composition_count_targets(self, batch) -> torch.Tensor:
        """Return exact graph-wise element counts without introducing a composition condition."""
        counts = torch.zeros((batch.num_graphs, self.atom_types), dtype=torch.long, device=batch.batch.device)
        one_hot = F.one_hot(batch.atom_types, self.atom_types).to(dtype=counts.dtype)
        counts.index_add_(0, batch.batch, one_hot)
        return counts

    def composition_count_loss(self, logits: torch.Tensor, batch) -> tuple[torch.Tensor, torch.Tensor]:
        """Cross entropy for the graph-level distribution of each element count."""
        expected = (batch.num_graphs, self.atom_types)
        if logits.ndim != 3 or logits.shape[:2] != expected:
            raise ValueError(f"composition logits must start with {expected}, got {tuple(logits.shape)}")
        target = self.composition_count_targets(batch)
        if int(target.max()) >= logits.shape[-1]:
            raise ValueError("composition head cannot represent the batch atom count")
        loss = F.cross_entropy(logits.reshape(-1, logits.shape[-1]), target.reshape(-1))
        return loss, target

    def map_composition_counts(
        self, logits: torch.Tensor, atom_count: int, gumbel: torch.Tensor | None = None
    ) -> torch.Tensor:
        """Draw a count vector conditioned exactly on a known total atom count.

        Independent element-count logits are projected to their maximum-score
        constrained joint state ``sum_k n_k = atom_count`` by dynamic
        programming.  Optional Gumbels make this a stochastic draw while
        preserving the count constraint.  This is a graph-level latent
        variable generated from the condition, never an externally supplied
        composition.
        """
        if logits.shape != (self.atom_types, logits.shape[-1]):
            raise ValueError("composition logits must have shape [atom_types, max_count + 1]")
        if atom_count < 1 or atom_count >= logits.shape[-1]:
            raise ValueError("atom_count is outside the composition-head support")
        score = logits[:, : atom_count + 1]
        if gumbel is not None:
            if gumbel.shape != logits.shape:
                raise ValueError("composition Gumbels must match composition logits")
            score = score + gumbel[:, : atom_count + 1]
        # The panel is tiny, but this dynamic program also covers the current
        # fixed-atom-count production sampler without enumerating all count
        # histograms.  It deliberately lives outside autograd (sampling only).
        best = score.new_full((atom_count + 1,), -float("inf"))
        best[0] = 0.0
        choices: list[torch.Tensor] = []
        for element in range(self.atom_types):
            updated = score.new_full((atom_count + 1,), -float("inf"))
            selected = torch.zeros((atom_count + 1,), dtype=torch.long, device=score.device)
            for total in range(atom_count + 1):
                possible = torch.arange(total + 1, device=score.device)
                values = best[total - possible] + score[element, possible]
                updated[total], selected[total] = values.max(dim=0)
            best = updated
            choices.append(selected)
        counts = torch.zeros((self.atom_types,), dtype=torch.long, device=score.device)
        total = atom_count
        for element in range(self.atom_types - 1, -1, -1):
            count = int(choices[element][total])
            counts[element] = count
            total -= count
        if total != 0 or int(counts.sum()) != atom_count:
            raise RuntimeError("constrained composition decoder failed to conserve atom count")
        return counts

    def _sampling_noise(
        self,
        batch,
        steps: int,
        generator: torch.Generator | None,
    ) -> DiscreteSamplingNoise:
        device = batch.batch.device
        return DiscreteSamplingNoise(
            reveal_uniform=torch.rand((steps, batch.atom_types.numel()), device=device, generator=generator),
            categorical_uniform=torch.rand(
                (steps, batch.atom_types.numel(), self.atom_types), device=device, generator=generator
            ),
        )

    def sample(
        self,
        model,
        batch,
        *,
        steps: int,
        noise: DiscreteSamplingNoise | None = None,
        generator: torch.Generator | None = None,
        graph_counts: torch.Tensor | None = None,
        return_trajectory: bool = False,
    ) -> CrystalFlowState | tuple[CrystalFlowState, list[CrystalFlowState]]:
        """Sample the discrete path with exact per-step mask reveal hazards."""
        if steps < 1:
            raise ValueError("steps must be positive")
        if noise is None:
            noise = self._sampling_noise(batch, steps, generator)
        expected_reveal = (steps, batch.atom_types.numel())
        expected_categorical = (steps, batch.atom_types.numel(), self.atom_types)
        if noise.reveal_uniform.shape != expected_reveal or noise.categorical_uniform.shape != expected_categorical:
            raise ValueError("sampling-noise tensors do not match steps, atoms, and vocabulary")
        if graph_counts is not None:
            if graph_counts.shape != (batch.num_graphs, self.atom_types):
                raise ValueError("graph_counts must have one chemical count vector per graph")
            node_counts = torch.bincount(batch.batch, minlength=batch.num_graphs)
            if bool((graph_counts < 0).any()) or not torch.equal(graph_counts.sum(-1).to(node_counts.dtype), node_counts):
                raise ValueError("each graph-count vector must be non-negative and conserve its atom count")
            remaining = graph_counts.clone().to(dtype=torch.long)
        else:
            remaining = None
        tokens = torch.full_like(batch.atom_types, self.mask_index)
        trajectory = [self._state(tokens, batch)] if return_trajectory else []
        with torch.no_grad():
            for step in range(steps):
                time_value = step / steps
                time = torch.full((batch.num_graphs,), time_value, device=batch.batch.device)
                state = self._state(tokens, batch)
                logits = self.posterior_logits(model, state, batch, time)
                log_probability = torch.log_softmax(logits, dim=-1)
                # For the linear schedule alpha(t)=t, this is exactly
                # (alpha(t + dt)-alpha(t))/(1-alpha(t)).  The final step is 1.
                reveal_probability = 1.0 / (steps - step)
                reveal = (tokens == self.mask_index) & (noise.reveal_uniform[step] < reveal_probability)
                uniforms = noise.categorical_uniform[step].clamp_(1e-7, 1.0 - 1e-7)
                gumbel = -torch.log(-torch.log(uniforms))
                if remaining is None:
                    proposed = (log_probability + gumbel).argmax(dim=-1)
                    tokens = torch.where(reveal, proposed, tokens)
                else:
                    # Choose every newly revealed element jointly from the
                    # remaining composition slots.  Dummy rows leave unused
                    # slots untouched, so all intermediate and terminal
                    # states conserve the graph-level composition latent.
                    from scipy.optimize import linear_sum_assignment

                    for graph in range(batch.num_graphs):
                        nodes = torch.nonzero((batch.batch == graph) & reveal, as_tuple=False).flatten()
                        if nodes.numel() == 0:
                            continue
                        slots = torch.repeat_interleave(
                            torch.arange(self.atom_types, device=tokens.device), remaining[graph]
                        )
                        slot_count = slots.numel()
                        if nodes.numel() > slot_count:
                            raise RuntimeError("more reveal events than remaining composition slots")
                        score = log_probability.new_zeros((slot_count, slot_count))
                        score[: nodes.numel()] = (log_probability[nodes] + gumbel[nodes])[:, slots]
                        row, column = linear_sum_assignment((-score).detach().cpu().numpy())
                        row = torch.as_tensor(row, device=tokens.device)
                        column = torch.as_tensor(column, device=tokens.device)
                        chosen_columns = column[row < nodes.numel()]
                        chosen = slots[chosen_columns]
                        tokens[nodes] = chosen
                        remaining[graph].index_add_(0, chosen, -torch.ones_like(chosen, dtype=remaining.dtype))
                if return_trajectory:
                    trajectory.append(self._state(tokens, batch))
        if bool((tokens == self.mask_index).any()):
            raise RuntimeError("absorbing discrete sampler left mask tokens at t=1")
        if remaining is not None and bool(remaining.any()):
            raise RuntimeError("constrained discrete sampler did not consume every composition slot")
        result = self._state(tokens, batch)
        return (result, trajectory) if return_trajectory else result
